config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :favorites, only: [:create]

  resources :listings do
    resources :reviews, only: [:new, :create]
  end
  # post '/listings/:listing_id/reviews', to: 'reviews#create', as: '/listings/:listing_id'


  resources :favorite_listings, only: [:create, :destroy]

  get '/' => 'users#index'

  get '/signup', to: 'users#new'
  get '/home', to: 'users#index'

  resources :users, except: [:destroy]

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations do
    resources :messages
  end


end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user, -> { where realtor: true}
  has_many :reviews
  has_many :favorites
  has_many_attached :images

  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :availability, presence: true

  def address_s
    self.address_line_1 + ", " + self.address_line_2
  end

  def listing_avg_rating
    if ratings.count != 0
      (ratings.inject { |sum, rating| sum + rating } / ratings.length).to_f.round(1)
    else
      nil
    end
  end

  private
  def ratings
    #code
    self.reviews.collect do |review|
      review.review_avg_rating
    end
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  helper_method :fetch_review_listing
  before_action :require_user
  before_action :fetch_listing, only: [:edit, :show, :update, :destroy]
  before_action :require_realtor, only: [:new, :create, :edit, :update, :destroy]

  def index
    #code
    @listings = Listing.all
  end

  def new
    #code
    @listing = Listing.new
  end

  def create
    #code
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.images.attach(params[:listing][:images])
    if @listing.save
      redirect_to @listing
    else
      render :new
    end
  end

  def show
    #code
  end

  def edit

  end

  def update

    #code
    @listing.update(listing_params)
    if params[:listing][:images]
      @listing.images.attach(params[:listing][:images])
    end
      if @listing.save
        redirect_to @listing
      else
        render :edit
      end
  end

  def destroy
    @listing.destroy
    redirect_to '/home'
  end

  private
  # def fetch_review_listing
  #   #code
  #   byebug
  #   @review_listing = Listing.find(params[:listing_id])
  # end

  def fetch_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:address_line_1, :address_line_2, :city, :state, :zipcode, :price, :availability, :description)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<div class="container">

<h2>Edit Listing</h2>

<%= form_for @listing do |f| %>
  <%= f.label :address_line_1 %>
  <%= f.text_field :address_line_1 %>
  <br>
  <%= f.label :address_line_2 %>
  <%= f.text_field :address_line_2 %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
   <br>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br>
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>
  <br>
  <%= f.label :price %>
  $<%= f.text_field :price %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :availability %>
  <%= f.text_field :availability %>
  <br>
  <%= f.file_field :images, multiple: true %><br>

  <%= f.submit %>

<% end %>

</div>

app/views/listings/index.html.erb
<h2>Listing Index Page</h2>

<% @listings.each do |listing| %>
  <%= link_to listing.address_s, listing_path(listing) %>
  <br>
<% end %>

app/views/listings/new.html.erb
<div class="container">

<h2>Create A New Listing!</h2>

<%= form_for @listing do |f| %>
  <%= f.label :address_line_1 %>
  <%= f.text_field :address_line_1 %>
  <br>
  <%= f.label :address_line_2 %>
  <%= f.text_field :address_line_2 %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
   <br>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br>
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>
  <br>
  <%= f.label :price %>
  $<%= f.text_field :price %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :availability %>
  <%= f.text_field :availability %>
  <br>
  <%= f.file_field :images, multiple: true %><br>

  <%= f.submit %>

<% end %>

</div>

app/views/listings/show.html.erb
<div class="container">

<h2><%= @listing.address_s %></h2>
<h2><%= @listing.city %>, <%= @listing.state %>, <%= @listing.zipcode %></h2>
<hr>
<% if current_user.realtor && current_user.id == @listing.user_id %>
  <%= link_to "Edit", edit_listing_path(@listing) %> |
  <%= link_to "Delete", listing_path(@listing), method: 'delete' %>
  <br>
<% end %>

<% if @listing.listing_avg_rating != nil %>

<h3>Overall Rating of <%= @listing.listing_avg_rating %> / 5.0!</h3>
<br>

<% end %>


<!-- ADD TO FAVES OR REMOVE  -->

<% if !current_user.realtor %>

<% unless current_user.favorite_listings.exists?(id: @listing.id) %>
<%= button_to '🖤 Add to favorites', favorite_listings_path(listing_id: @listing), method: :post %>
<% else %>
<%= button_to '🗑 Remove from favorites', favorite_listing_path(@listing), method: :delete %>
<% end %>

<br>

<% end %>

<!-- IMAGES -->


<% if @listing.images.attached? %>

<div class="tech-slideshow">
  <!-- <div class="mover-1">

  </div> -->
  <div class="mover-2">
    <% @listing.images.each do |image| %>
      <%= image_tag image%>
    <% end %>
  </div>

</div>

<% end %>

<hr>
<!-- LISTING INFO -->

<h3>Realtor:</h3>
<%= link_to @listing.user.user_s, user_path(@listing.user) %>

<h3>Price: </h3>$<%= @listing.price %><br>
<h3>Description: </h3><%= @listing.description %><br><br>
<h3>Availability: </h3><%= @listing.availability %>


<!-- REVIEWS -->


<h2>Reviews:</h2>
<% if !current_user.realtor %>
<%= link_to "Add A Review", new_listing_review_path(@listing) %>
<br><br>
<% end %>

<ul>
<% @listing.reviews.each do |review| %>
  <li>
    Overall: <%= review.review_avg_rating %>/5.0 |
  <%= link_to review.user.first_name, review.user %>  wrote: <br>
  Title: <%= review.title %><br><br>
  Ratings:
  <table>
    <tr>
      <td>Cleanliness: <%= review.cleanlines %></td>
      <td>Communication: <%= review.communication %></td>
    </tr>
    <br>
    <tr>
      <td>Location: <%= review.location %></td>
      <td>Value: <%= review.value %></td>
    </tr>
  </table>

  <br>
  Comment: <br> <%= review.content %><br>
  <%= review.published_at %><br>
</li>

<% end %>

</ul>

</div>