config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :favorites, only: [:create]

  resources :listings do
    resources :reviews, only: [:new, :create]
  end
  # post '/listings/:listing_id/reviews', to: 'reviews#create', as: '/listings/:listing_id'


  resources :favorite_listings, only: [:create, :destroy]

  get '/' => 'users#index'

  get '/signup', to: 'users#new'
  get '/home', to: 'users#index'

  resources :users, except: [:destroy]

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations do
    resources :messages
  end


end

app/models/conversation.rb
class Conversation < ApplicationRecord

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    #code
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end



end

app/views/conversations/index.html.erb
<div class="container">
<h2>All Messages</h2>
<i class="fas fa-envelope"></i> <%= link_to "Create a new Message", new_conversation_path %>
<hr>

<h3>Inbox: </h3>
<ul>
  <% @conversations.each do |conversation| %>
      <li>
          <h3><%= link_to conversation.subject, conversation_path(conversation) %></h3>
      </li>

  <% end %>
</ul>

<div>

app/views/conversations/new.html.erb
<div class="container">

<h2>New Message</h2>

<%= form_tag conversations_path, method: :post do %>
    <div>
        <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :first_name) %>
    </div>

    <div>
     <%= text_field_tag :subject, nil, placeholder: "Subject" %>
    </div>

    <div>
     <%= text_area_tag :body, nil, placeholder: "Leave a message" %>
    </div>

    <%= submit_tag %>
<% end %>

</div>

app/views/conversations/show.html.erb
<div class="container">

<%= link_to "All Messages", conversations_path %>
<br>

<h2><%= @conversation.subject %></h2>

<% @conversation.receipts_for(current_user).each do |receipt| %>
    <div>
        <div>
          <%= receipt.message.sender.user_s %> wrote:
        </div>
        <p><%= receipt.message.body %></p>
    </div>
<% end %>

<%= form_tag conversation_messages_path(@conversation) do %>
  <div>
    <%= text_area_tag :body %>
  </div>

  <%= submit_tag %>

<% end %>

</div>