config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :favorites, only: [:create]

  resources :listings do
    resources :reviews, only: [:new, :create]
  end
  # post '/listings/:listing_id/reviews', to: 'reviews#create', as: '/listings/:listing_id'


  resources :favorite_listings, only: [:create, :destroy]

  get '/' => 'users#index'

  get '/signup', to: 'users#new'
  get '/home', to: 'users#index'

  resources :users, except: [:destroy]

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :conversations do
    resources :messages
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :listings, -> { where realtor: true }, dependent: :delete_all
  has_many :favorites #, -> { where realtor: false }
  has_many :favorite_listings, through: :favorites, source: :favorited, source_type: 'Listing'

  acts_as_messageable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # validates :password, presence: true

  def user_s
    self.first_name + " " + self.last_name
  end

  def realtor?
    self.realtor == true
  end

  def regular?
    self.realtor == false
  end

  def mailboxer_email(obj)
    nil
  end

  def realtor_listings
    if self.realtor
      Listing.all.select do |listing|
        listing.user_id == self.id
      end
    end
  end

  def regular_favorites
    if !self.realtor
      Favorite.all.select do |favorite|
        favorite.user_id == self.id
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:index, :edit, :show, :update]

  before_action :fetch_user, only: [:edit, :update, :show]

  def index
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to edit_user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    #code
  end

  def edit

  end

  def update
    param = nil
    if @user.realtor?
      param = update_realtor_user_params
    else
      param = update_norm_user_params
    end

    @user.update(param)
    if @user.save
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # def destroy
  #   session[:user_id] = nil
  #   @user.destroy
  #   redirect_to '/signup'
  # end


  private
  def fetch_user
    @user = User.find(params[:id])
  end

  def new_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :realtor)
  end

  def update_norm_user_params
    #code
    params.require(:user).permit( :first_name, :last_name, :phone_number)
  end

  def update_realtor_user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :firm)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">

<h2>Update your profile information:</h2>
<hr>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%# f.label :email %>
  <%# f.email_field :email %>
  <br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <br>

  <!-- CHECK IF THEY'RE A REALTOR -->
  <% if @user.realtor?  %>
    <%= f.label :firm %>
    <%= f.text_field :firm %>
    <br>
  <% end %>

  <%= f.submit "Save" %>
<% end %>

<div>

app/views/users/index.html.erb
<div class="container">

<h2>Hello, <%= current_user.first_name %>!</h2>


<hr>
<h2 align="center">Available Listings</h2>

  <div>
    <table width="80%" border="1px" align="center">
      <tr>
        <td align="center">Listing Address</td>
        <td align="center">Listing Preview</td>
      </tr>
      <% Listing.all.each do |listing| %>
      <tr>
        <td align="center" width="30%"><%= link_to listing.address_s, listing_path(listing) %> <br> </td>
        <% if listing.images.attached? %>
        <td align="center", width="30%"><%= image_tag listing.images[0], size: "100x100" %></td>
        <% else %>
        <td>No Images</td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>

  </div>

app/views/users/new.html.erb
<div class="users-new">
<center>

  <h1>Listings R Us</h1>
<div class="users-new-form">

<%= form_for @user do |f| %>

  <table>
    <tr>
      <td align="right"><%= f.label :first_name, "First Name: " %> &nbsp; </td>
      <td align="left"><%= f.text_field :first_name, placeholder: "First Name" %> </td>
    </tr>

    <tr>
      <td align="right"><%= f.label :last_name, "Last Name: " %> &nbsp; </td>
      <td align="left"><%= f.text_field :last_name, placeholder: "Last Name" %>
       </td>
    </tr>

    <tr>
      <td align="right"><%= f.label :email, "E-mail: " %> &nbsp; </td>
      <td align="left"><%= f.email_field :email, placeholder: "E-mail address" %>
       </td>
    </tr>

    <tr>
      <td align="right"><%= f.label :password, "Create Password:" %> &nbsp; </td>
      <td align="left"><%= f.password_field :password, placeholder: "Password" %>
      </td>
    </tr>

</table>

  <br>
  <%= f.label :realtor, "Are you a realtor?" %>
  <br>
  <%= f.radio_button :realtor, true %> Yes
  <%= f.radio_button :realtor, false, checked: true %> No
  <br><br>
  <%= f.submit "Sign Up" %>
<% end %>

<br>

Already have an account? <%= link_to "Log In", '/login' %>

</div>

</center>

</div>

app/views/users/show.html.erb
<div class="container">

<h2><%= @user.first_name %>'s Profile</h2>

<% if @user.id == current_user.id %>
   <i class="fas fa-user-edit"></i> <%= link_to "Edit profile", edit_user_path(@user) %>

   <% if current_user.realtor %>
     | <i class="fas fa-plus-circle"></i> <%= link_to "Create A New Listing", new_listing_path %>
   <% end %>

<% end %>

<hr>

<h4>Name: <%= @user.user_s %> </h4>
<h4>Phone: <%= @user.phone_number %></h4>
<h4>Email: <%= @user.email %></h4>
<% if @user.realtor? %>
<h4>Firm: <%= @user.firm %></h4>
<% end %>


<% if @user.realtor %>
<hr>
  <h3>My Listings:</h3>

  <ul>
  <% @user.realtor_listings.each do |listing| %>
    <li>
      <h4><%= link_to listing.address_s, listing %></h4>
    </li>
  <% end %>
</ul>
<% end %>

<% if !@user.realtor %>
<hr>
  <h3>My Favorites:</h3>
  <ul>
  <% @user.regular_favorites.each do |favorite| %>
    <li>
      <h4><%= link_to favorite.favorited.address_s, favorite.favorited %></h4>
    </li>
  <% end %>
</ul>
<% end %>

</div>